language: node_js

node_js:
  - stable

cache: npm

script:
  - npm run build

  
#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file_glob: true
#  file: build/*
#  skip_cleanup: true
#  on:
#    tags: true